const ERRORS = 'ERRORS';
const AUTH_ERROR = 'AUTH_ERROR';

const SET_CURRENT_USER = 'SET_CURRENT_USER';
const SUCCESSFUL_REGISTER = 'SUCCESSFUL_REGISTER';
const FAILURE_REGISTER = 'FAILURE_REGISTER';

const GET_PRODUCT = 'GET_PRODUCT';
const PRODUCTS = 'PRODUCTS';

export {
  ERRORS,
  AUTH_ERROR,
  GET_PRODUCT,
  PRODUCTS,
  SET_CURRENT_USER,
  SUCCESSFUL_REGISTER,
  FAILURE_REGISTER,
};
